### ISSUE TITLE
Error [ERR_REQUIRE_ESM] & TypeError: Unknown file extension ".ts" with latest version 3.0.0

### ISSUE THREAD

**Issue by virajshelke** [sindresorhus/fnv1a#14]
When I try to build my typescript code and run it I am getting the following error.

```bash
const fnv1a_1 = __importDefault(require("@sindresorhus/fnv1a"));
                                ^

Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules\@sindresorhus\fnv1a\index.js from dist\utils\load-balancer.js not supported.
Instead change the require of index.js in dist\utils\load-balancer.js to a dynamic import() which is available in all CommonJS modules.
```

My `tsconfig.json` config is,

```json
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "lib": ["ES2020"],
    "types": ["reflect-metadata", "mocha"],
    "strict": true,
    "sourceMap": true,
    "outDir": "dist",
    "moduleResolution": "node",
    "removeComments": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "baseUrl": "."
  },
  "exclude": ["node_modules"],
  "include": ["src/**/*"]
}

```

Surprisingly my test cases are also not able tp run. Mocha runner fails with following error,

```bash
TypeError: Unknown file extension ".ts" for tests\end-to-end\change-notification.test.ts
    at new NodeError (node:internal/errors:371:5)
    at Object.file: (node:internal/modules/esm/get_format:72:15)
    at defaultGetFormat (node:internal/modules/esm/get_format:85:38)
    at defaultLoad (node:internal/modules/esm/load:13:42)
    at ESMLoader.load (node:internal/modules/esm/loader:303:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:230:58)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:244:11)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at formattedImport (node_modules\mocha\lib\esm-utils.js:7:14)
    at Object.exports.loadFilesAsync (node_modules\mocha\lib\esm-utils.js:55:20)
    at singleRun (node_modules\mocha\lib\cli\run-helpers.js:125:3)
    at Object.exports.handler (node_modules\mocha\lib\cli\run.js:362:5)
```

Note - The same codebase with no changes in the code works absolutely fine with `@sindresorhus/fnv1a` version `2.0.1`
node - v16.13.0 LTS
npm - v8.1.0

Any idea as to why is it breaking in runtime & breaking my tests? My `tsc` compilation works fine!

@sindresorhus

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by virajshelke** [comment]
@sindresorhus Thanks for the quick reply & guidance! That helps! Will look into it 👍 :)
